/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-3')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-3')['BButtonGroup']
    BContainer: typeof import('bootstrap-vue-3')['BContainer']
    BForm: typeof import('bootstrap-vue-3')['BForm']
    BFormFloatingLabel: typeof import('bootstrap-vue-3')['BFormFloatingLabel']
    BFormGroup: typeof import('bootstrap-vue-3')['BFormGroup']
  }
}
